#!/bin/bash

# Update package lists
 apt update

# Install Nginx
 yum install -y nginx

# Start Nginx service
 systemctl start nginx

# Enable Nginx to start on system boot
 systemctl enable nginx

# Print the status of Nginx service
 systemctl status nginx

